### ISSUE TITLE
Dead links in Disqus iframe

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-blog#15]
Many of the links to other blogposts displayed in Disqus iframe are dead.
For example in this post https://blog.bitrise.io/add-a-plus-layer-of-security-to-your-bitrise-account:
![image](https://user-images.githubusercontent.com/3340954/32415531-58800c16-c23b-11e7-8b1a-bd1a2c7ecd5d.png)
3 of 4 links there point to 404 error pages:

1. https://blog.bitrise.io/2015/12/15/virtual-machine-update-dec-19.html
2. http://devcenter.bitrise.io/docs/step-dev.html
3. https://blog.bitrise.io/2016/08/09/automatic-ipa-re-signing-and-ios-scheme-generation.html

BTW shouldn't blog 404 error pages be styled like those on bitrise.io? E.g. http://www.bitrise.io/foo

**Comment by erosdome** [comment]
Hi, thanks for reporting the issue, they are in fact dead links. We will resolve this issue ASAP.

**Comment by erosdome** [comment]
Hi, checked a couple of blogposts, including the mentioned article, links seem to be working correctly. If there turns up to be any other dead link, I'll reopen the issue.
