### ISSUE TITLE
Typo in "Test a PR manually before merging it" post

### ISSUE THREAD

**Issue by koral--** [bitrise-io/bitrise-blog#16]
https://blog.bitrise.io/test-a-pr-manually-before-merging-it
![image](https://user-images.githubusercontent.com/3340954/32670869-6f9492e2-c645-11e7-8334-d8f845a866f2.png)

environmtent -> environment

**Comment by viktorbenei** [comment]
Thanks for the report @koral-- ! ;)

**Comment by annabatki** [comment]
Thanks, @koral-- , I fixed this. :)

**Comment by viktorbenei** [comment]
🎉 :)
